JavaScript typing exercise. Can't seem to get the underline class to …
PeterVila/c0821-code-solutions pull request #48
Opened 2021-08-31 22:35 UTC by PeterVila

https://user-images.githubusercontent.com/42393951/131584472-a43ac323-83cc-48ac-b935-dadbe4a11a16.mp4

…be added with current index. Added a completion alert with % error

2021-08-31 22:46 UTC, codingcodymiller requested changes
Great start!! A few notes for you:

2021-08-31 22:46 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +      alert('Your typing % is: ' + Math.round(27 / attempts * 100) + ' %');
Ewwwwwwwwwwwww, no `alert` should ever be present in modern code. You should make a modal for this! Thankfully the process to make one should be fresh in your mind 🤓

2021-08-31 22:46 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +  $text[value + 1].className = 'underline';
I don;t see any styling for `underline`, this line can likely be removed.

2021-08-31 22:46 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +    $score.innerHTML = 'Score: ' + value + '/27';
Using the `innerHTML` property is a big no-no. It leaves you open to script injections, which is a bad security risk. Instead, you should put an element like a `span` around where the score would be in this element, then just update the `textContent` of that one element.

2021-08-31 23:52 UTC, PeterVila commented
https://user-images.githubusercontent.com/42393951/131590331-c61d4265-1b3f-451d-9d95-c3f32ca3bb29.mp4

2021-09-01 00:14 UTC, codingcodymiller requested changes
Great work!! A few notes for you:

2021-09-01 00:14 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +document.addEventListener('keydown', function (e) {
Remember, named functions are preferred over anonymous functions

2021-09-01 00:14 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +      });
Oh nooooooo 😱  

`location.reload` is a forbidden tool. It completely reloads the page, which is an **_extremely_** intensive process for the browser. Instead, you should reset all your elements to the state they would be in when the page loads using javascript, and reset the value of any variables in JavaScript to what their initial value would be as well.

2021-09-01 00:14 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +});
This will need to be adjusted too, per my previous comment.

2021-09-01 18:09 UTC, codingcodymiller requested changes

2021-09-01 18:09 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +  if (e) {
This conditional is likely not necessary 🤔 

When would you not get an event object? This seems like it would always trigger the conditional.

2021-09-01 18:09 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +    $opacity.className = 'text';
This can probably just be done for both "retry" buttons, that way you only need one named function for resetting the app.

2021-09-01 22:57 UTC, codingcodymiller requested changes

2021-09-01 22:57 UTC, codingcodymiller commented on javascript-typing-tutor/script.js
> +  $opacity.className = 'text';
Don't know if you missed my last comment, but you can just do this for both retry buttons so that you only have one event handler for "retry"

2021-09-02 18:14 UTC, codingcodymiller approved these changes
Great work!!!

2021-09-02 18:17 UTC, merged